name: video
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py310h06a4308_0
  - aiohttp=3.11.10=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=5.0.1=py310h06a4308_0
  - attrs=24.3.0=py310h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - discord.py=2.3.2=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - ffmpeg=4.3.2=hca11adc_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - multidict=6.1.0=py310h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.2=py310h06a4308_0
  - pip=25.1=pyhc872135_2
  - pluggy=1.5.0=py310h06a4308_0
  - propcache=0.3.1=py310h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pytest=8.3.4=py310h06a4308_0
  - python=3.10.16=he870216_1
  - python-dotenv=1.1.0=pyh29332c3_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - tomli=2.0.1=py310h06a4308_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yarl=1.18.0=py310h5eee18b_0
  - yt-dlp=2025.5.22=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
prefix: /home/tycho/anaconda3/envs/video
