name: video
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - discord.py=2.3.2
  - exceptiongroup=1.2.0
  - ffmpeg=4.3.2
  - freetype=2.13.3
  - frozenlist=1.5.0
  - gmp=6.3.0
  - gnutls=3.6.15
  - idna=3.7
  - iniconfig=1.1.1
  - lame=3.100
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libxcb=1.17.0
  - multidict=6.1.0
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=3.0.16
  - packaging=24.2
  - pip=25.1
  - pluggy=1.5.0
  - propcache=0.3.1
  - pthread-stubs=0.3
  - pytest=8.3.4
  - python=3.10.16
  - python-dotenv=1.1.0
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tomli=2.0.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - wheel=0.45.1
  - x264=1!161.3030
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yarl=1.18.0
  - yt-dlp=2025.5.22
  - zlib=1.2.13
prefix: /home/tycho/anaconda3/envs/video
